/* This file was generated by upb_generator from the input file:
 *
 *     update_metadata.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated.
 * NO CHECKED-IN PROTOBUF GENCODE */

#include <stddef.h>
#include "upb/generated_code_support.h"
#include "update_metadata.upb_minitable.h"

// Must be last.
#include "upb/port/def.inc"

extern const UPB_PRIVATE(upb_GeneratedExtensionListEntry)* UPB_PRIVATE(upb_generated_extension_list);
typedef struct {
  upb_MiniTableField fields[2];
} chromeos_0update_0engine__Extent_msg_init_Fields;

static const chromeos_0update_0engine__Extent_msg_init_Fields chromeos_update_engine_Extent__fields = {{
  {1, 16, 64, kUpb_NoSub, 4, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)},
  {2, 24, 65, kUpb_NoSub, 4, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)},
}};

const upb_MiniTable chromeos_0update_0engine__Extent_msg_init = {
  &chromeos_update_engine_Extent__fields.fields[0],
  32, 2, kUpb_ExtMode_NonExtendable, 2, UPB_FASTTABLE_MASK(24), 0,
#ifdef UPB_TRACING_ENABLED
  "chromeos_update_engine.Extent",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0010000000000008, &upb_DecodeFast_Varint64_Scalar_Tag1Byte},
    {0x0018000001000010, &upb_DecodeFast_Varint64_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
  })
};

typedef struct {
  upb_MiniTableField fields[1];
  upb_MiniTableSubInternal subs[1];
} chromeos_0update_0engine__Signatures_msg_init_Fields;

static const chromeos_0update_0engine__Signatures_msg_init_Fields chromeos_update_engine_Signatures__fields = {{
  {1, 8, 0, UPB_SIZE(3, 4), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
 },
  {
  {.UPB_PRIVATE(submsg) = &chromeos_0update_0engine__Signatures__Signature_msg_init},
}};

const upb_MiniTable chromeos_0update_0engine__Signatures_msg_init = {
  &chromeos_update_engine_Signatures__fields.fields[0],
  16, 1, kUpb_ExtMode_NonExtendable, 1, UPB_FASTTABLE_MASK(255), 0,
#ifdef UPB_TRACING_ENABLED
  "chromeos_update_engine.Signatures",
#endif
};

typedef struct {
  upb_MiniTableField fields[3];
} chromeos_0update_0engine__Signatures__Signature_msg_init_Fields;

static const chromeos_0update_0engine__Signatures__Signature_msg_init_Fields chromeos_update_engine_Signatures_Signature__fields = {{
  {1, 12, 64, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {2, UPB_SIZE(20, 24), 65, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {3, 16, 66, kUpb_NoSub, 7, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
}};

const upb_MiniTable chromeos_0update_0engine__Signatures__Signature_msg_init = {
  &chromeos_update_engine_Signatures_Signature__fields.fields[0],
  UPB_SIZE(32, 40), 3, kUpb_ExtMode_NonExtendable, 3, UPB_FASTTABLE_MASK(24), 0,
#ifdef UPB_TRACING_ENABLED
  "chromeos_update_engine.Signatures.Signature",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x000c000000000008, &upb_DecodeFast_Varint32_Scalar_Tag1Byte},
    {0x0018000001000012, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x001000000200001d, &upb_DecodeFast_Fixed32_Scalar_Tag1Byte},
  })
};

typedef struct {
  upb_MiniTableField fields[2];
} chromeos_0update_0engine__PartitionInfo_msg_init_Fields;

static const chromeos_0update_0engine__PartitionInfo_msg_init_Fields chromeos_update_engine_PartitionInfo__fields = {{
  {1, UPB_SIZE(24, 32), 64, kUpb_NoSub, 4, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)},
  {2, UPB_SIZE(12, 16), 65, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
}};

const upb_MiniTable chromeos_0update_0engine__PartitionInfo_msg_init = {
  &chromeos_update_engine_PartitionInfo__fields.fields[0],
  UPB_SIZE(32, 40), 2, kUpb_ExtMode_NonExtendable, 2, UPB_FASTTABLE_MASK(24), 0,
#ifdef UPB_TRACING_ENABLED
  "chromeos_update_engine.PartitionInfo",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0020000000000008, &upb_DecodeFast_Varint64_Scalar_Tag1Byte},
    {0x0010000001000012, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
  })
};

typedef struct {
  upb_MiniTableField fields[9];
  upb_MiniTableSubInternal subs[3];
} chromeos_0update_0engine__InstallOperation_msg_init_Fields;

static const chromeos_0update_0engine__InstallOperation_msg_init_Fields chromeos_update_engine_InstallOperation__fields = {{
  {1, 12, 64, UPB_SIZE(27, 28), 14, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {2, UPB_SIZE(40, 48), 65, kUpb_NoSub, 4, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)},
  {3, UPB_SIZE(48, 56), 66, kUpb_NoSub, 4, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)},
  {4, UPB_SIZE(16, 64), 0, UPB_SIZE(19, 21), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {5, UPB_SIZE(56, 72), 67, kUpb_NoSub, 4, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)},
  {6, UPB_SIZE(20, 80), 0, UPB_SIZE(14, 17), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {7, UPB_SIZE(64, 88), 68, kUpb_NoSub, 4, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)},
  {8, UPB_SIZE(24, 16), 69, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {9, 32, 70, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
 },
  {
  {.UPB_PRIVATE(subenum) = &chromeos_0update_0engine__InstallOperation__Type_enum_init},
  {.UPB_PRIVATE(submsg) = &chromeos_0update_0engine__Extent_msg_init},
  {.UPB_PRIVATE(submsg) = &chromeos_0update_0engine__Extent_msg_init},
}};

const upb_MiniTable chromeos_0update_0engine__InstallOperation_msg_init = {
  &chromeos_update_engine_InstallOperation__fields.fields[0],
  UPB_SIZE(72, 96), 9, kUpb_ExtMode_NonExtendable, 9, UPB_FASTTABLE_MASK(120), 1,
#ifdef UPB_TRACING_ENABLED
  "chromeos_update_engine.InstallOperation",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0030000001000010, &upb_DecodeFast_Varint64_Scalar_Tag1Byte},
    {0x0038000002000018, &upb_DecodeFast_Varint64_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0048000003000028, &upb_DecodeFast_Varint64_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0058000004000038, &upb_DecodeFast_Varint64_Scalar_Tag1Byte},
    {0x0010000005000042, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x002000000600004a, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
  })
};

typedef struct {
  upb_MiniTableField fields[4];
  upb_MiniTableSubInternal subs[3];
} chromeos_0update_0engine__CowMergeOperation_msg_init_Fields;

static const chromeos_0update_0engine__CowMergeOperation_msg_init_Fields chromeos_update_engine_CowMergeOperation__fields = {{
  {1, 12, 64, 12, 14, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {2, UPB_SIZE(16, 24), 65, UPB_SIZE(10, 11), 11, (int)kUpb_FieldMode_Scalar | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {3, UPB_SIZE(20, 32), 66, UPB_SIZE(8, 10), 11, (int)kUpb_FieldMode_Scalar | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {4, UPB_SIZE(24, 16), 67, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
 },
  {
  {.UPB_PRIVATE(subenum) = &chromeos_0update_0engine__CowMergeOperation__Type_enum_init},
  {.UPB_PRIVATE(submsg) = &chromeos_0update_0engine__Extent_msg_init},
  {.UPB_PRIVATE(submsg) = &chromeos_0update_0engine__Extent_msg_init},
}};

const upb_MiniTable chromeos_0update_0engine__CowMergeOperation_msg_init = {
  &chromeos_update_engine_CowMergeOperation__fields.fields[0],
  UPB_SIZE(32, 40), 4, kUpb_ExtMode_NonExtendable, 4, UPB_FASTTABLE_MASK(56), 0,
#ifdef UPB_TRACING_ENABLED
  "chromeos_update_engine.CowMergeOperation",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0010000003000020, &upb_DecodeFast_Varint32_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
  })
};

typedef struct {
  upb_MiniTableField fields[20];
  upb_MiniTableSubInternal subs[9];
} chromeos_0update_0engine__PartitionUpdate_msg_init_Fields;

static const chromeos_0update_0engine__PartitionUpdate_msg_init_Fields chromeos_update_engine_PartitionUpdate__fields = {{
  {1, UPB_SIZE(56, 24), 64, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {2, 11, 65, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {3, UPB_SIZE(64, 40), 66, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {4, UPB_SIZE(72, 56), 67, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {5, UPB_SIZE(16, 120), 0, 48, 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {6, UPB_SIZE(20, 128), 68, UPB_SIZE(46, 47), 11, (int)kUpb_FieldMode_Scalar | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {7, UPB_SIZE(24, 136), 69, UPB_SIZE(44, 46), 11, (int)kUpb_FieldMode_Scalar | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {8, UPB_SIZE(28, 144), 0, UPB_SIZE(42, 45), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {9, 12, 70, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {10, UPB_SIZE(32, 152), 71, UPB_SIZE(37, 41), 11, (int)kUpb_FieldMode_Scalar | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {11, UPB_SIZE(36, 160), 72, UPB_SIZE(35, 40), 11, (int)kUpb_FieldMode_Scalar | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {12, UPB_SIZE(80, 72), 73, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {13, 88, 74, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {14, UPB_SIZE(40, 168), 75, UPB_SIZE(27, 33), 11, (int)kUpb_FieldMode_Scalar | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {15, UPB_SIZE(44, 176), 76, UPB_SIZE(25, 32), 11, (int)kUpb_FieldMode_Scalar | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {16, UPB_SIZE(48, 16), 77, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {17, UPB_SIZE(96, 104), 78, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {18, UPB_SIZE(52, 184), 0, UPB_SIZE(17, 25), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {19, UPB_SIZE(104, 192), 79, kUpb_NoSub, 4, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)},
  {20, UPB_SIZE(112, 200), 80, kUpb_NoSub, 4, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)},
 },
  {
  {.UPB_PRIVATE(submsg) = &chromeos_0update_0engine__Signatures__Signature_msg_init},
  {.UPB_PRIVATE(submsg) = &chromeos_0update_0engine__PartitionInfo_msg_init},
  {.UPB_PRIVATE(submsg) = &chromeos_0update_0engine__PartitionInfo_msg_init},
  {.UPB_PRIVATE(submsg) = &chromeos_0update_0engine__InstallOperation_msg_init},
  {.UPB_PRIVATE(submsg) = &chromeos_0update_0engine__Extent_msg_init},
  {.UPB_PRIVATE(submsg) = &chromeos_0update_0engine__Extent_msg_init},
  {.UPB_PRIVATE(submsg) = &chromeos_0update_0engine__Extent_msg_init},
  {.UPB_PRIVATE(submsg) = &chromeos_0update_0engine__Extent_msg_init},
  {.UPB_PRIVATE(submsg) = &chromeos_0update_0engine__CowMergeOperation_msg_init},
}};

const upb_MiniTable chromeos_0update_0engine__PartitionUpdate_msg_init = {
  &chromeos_update_engine_PartitionUpdate__fields.fields[0],
  UPB_SIZE(120, 208), 20, kUpb_ExtMode_NonExtendable, 20, UPB_FASTTABLE_MASK(248), 1,
#ifdef UPB_TRACING_ENABLED
  "chromeos_update_engine.PartitionUpdate",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x001800000000000a, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x000b000001000010, &upb_DecodeFast_Bool_Scalar_Tag1Byte},
    {0x002800000200001a, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x0038000003000022, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x000c000006000048, &upb_DecodeFast_Bool_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0048000009000062, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x005800000a00006a, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x001000000d000180, &upb_DecodeFast_Varint32_Scalar_Tag2Byte},
    {0x006800000e00018a, &upb_DecodeFast_Bytes_Scalar_Tag2Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x00c000000f000198, &upb_DecodeFast_Varint64_Scalar_Tag2Byte},
    {0x00c80000100001a0, &upb_DecodeFast_Varint64_Scalar_Tag2Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
  })
};

typedef struct {
  upb_MiniTableField fields[3];
} chromeos_0update_0engine__DynamicPartitionGroup_msg_init_Fields;

static const chromeos_0update_0engine__DynamicPartitionGroup_msg_init_Fields chromeos_update_engine_DynamicPartitionGroup__fields = {{
  {1, 16, 64, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {2, UPB_SIZE(24, 32), 65, kUpb_NoSub, 4, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)},
  {3, UPB_SIZE(12, 40), 0, kUpb_NoSub, 12, (int)kUpb_FieldMode_Array | (int)kUpb_LabelFlags_IsAlternate | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
}};

const upb_MiniTable chromeos_0update_0engine__DynamicPartitionGroup_msg_init = {
  &chromeos_update_engine_DynamicPartitionGroup__fields.fields[0],
  UPB_SIZE(32, 48), 3, kUpb_ExtMode_NonExtendable, 3, UPB_FASTTABLE_MASK(24), 1,
#ifdef UPB_TRACING_ENABLED
  "chromeos_update_engine.DynamicPartitionGroup",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x001000000000000a, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x0020000001000010, &upb_DecodeFast_Varint64_Scalar_Tag1Byte},
    {0x002800003f00001a, &upb_DecodeFast_Bytes_Repeated_Tag1Byte},
  })
};

typedef struct {
  upb_MiniTableField fields[2];
} chromeos_0update_0engine__VABCFeatureSet_msg_init_Fields;

static const chromeos_0update_0engine__VABCFeatureSet_msg_init_Fields chromeos_update_engine_VABCFeatureSet__fields = {{
  {1, 9, 64, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {2, 10, 65, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
}};

const upb_MiniTable chromeos_0update_0engine__VABCFeatureSet_msg_init = {
  &chromeos_update_engine_VABCFeatureSet__fields.fields[0],
  16, 2, kUpb_ExtMode_NonExtendable, 2, UPB_FASTTABLE_MASK(24), 0,
#ifdef UPB_TRACING_ENABLED
  "chromeos_update_engine.VABCFeatureSet",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0009000000000008, &upb_DecodeFast_Bool_Scalar_Tag1Byte},
    {0x000a000001000010, &upb_DecodeFast_Bool_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
  })
};

typedef struct {
  upb_MiniTableField fields[7];
  upb_MiniTableSubInternal subs[2];
} chromeos_0update_0engine__DynamicPartitionMetadata_msg_init_Fields;

static const chromeos_0update_0engine__DynamicPartitionMetadata_msg_init_Fields chromeos_update_engine_DynamicPartitionMetadata__fields = {{
  {1, UPB_SIZE(12, 32), 0, UPB_SIZE(21, 22), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {2, 9, 64, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {3, 10, 65, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {4, UPB_SIZE(24, 16), 66, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {5, UPB_SIZE(16, 12), 67, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {6, UPB_SIZE(20, 40), 68, UPB_SIZE(7, 9), 11, (int)kUpb_FieldMode_Scalar | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {7, UPB_SIZE(32, 48), 69, kUpb_NoSub, 4, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)},
 },
  {
  {.UPB_PRIVATE(submsg) = &chromeos_0update_0engine__DynamicPartitionGroup_msg_init},
  {.UPB_PRIVATE(submsg) = &chromeos_0update_0engine__VABCFeatureSet_msg_init},
}};

const upb_MiniTable chromeos_0update_0engine__DynamicPartitionMetadata_msg_init = {
  &chromeos_update_engine_DynamicPartitionMetadata__fields.fields[0],
  UPB_SIZE(40, 56), 7, kUpb_ExtMode_NonExtendable, 7, UPB_FASTTABLE_MASK(56), 0,
#ifdef UPB_TRACING_ENABLED
  "chromeos_update_engine.DynamicPartitionMetadata",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0009000000000010, &upb_DecodeFast_Bool_Scalar_Tag1Byte},
    {0x000a000001000018, &upb_DecodeFast_Bool_Scalar_Tag1Byte},
    {0x0010000002000022, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x000c000003000028, &upb_DecodeFast_Varint32_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0030000005000038, &upb_DecodeFast_Varint64_Scalar_Tag1Byte},
  })
};

typedef struct {
  upb_MiniTableField fields[4];
} chromeos_0update_0engine__ApexInfo_msg_init_Fields;

static const chromeos_0update_0engine__ApexInfo_msg_init_Fields chromeos_update_engine_ApexInfo__fields = {{
  {1, UPB_SIZE(12, 16), 64, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {2, UPB_SIZE(24, 32), 65, kUpb_NoSub, 3, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)},
  {3, 9, 66, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {4, UPB_SIZE(32, 40), 67, kUpb_NoSub, 3, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)},
}};

const upb_MiniTable chromeos_0update_0engine__ApexInfo_msg_init = {
  &chromeos_update_engine_ApexInfo__fields.fields[0],
  UPB_SIZE(40, 48), 4, kUpb_ExtMode_NonExtendable, 4, UPB_FASTTABLE_MASK(56), 0,
#ifdef UPB_TRACING_ENABLED
  "chromeos_update_engine.ApexInfo",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x001000000000000a, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x0020000001000010, &upb_DecodeFast_Varint64_Scalar_Tag1Byte},
    {0x0009000002000018, &upb_DecodeFast_Bool_Scalar_Tag1Byte},
    {0x0028000003000020, &upb_DecodeFast_Varint64_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
  })
};

typedef struct {
  upb_MiniTableField fields[1];
  upb_MiniTableSubInternal subs[1];
} chromeos_0update_0engine__ApexMetadata_msg_init_Fields;

static const chromeos_0update_0engine__ApexMetadata_msg_init_Fields chromeos_update_engine_ApexMetadata__fields = {{
  {1, 8, 0, UPB_SIZE(3, 4), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
 },
  {
  {.UPB_PRIVATE(submsg) = &chromeos_0update_0engine__ApexInfo_msg_init},
}};

const upb_MiniTable chromeos_0update_0engine__ApexMetadata_msg_init = {
  &chromeos_update_engine_ApexMetadata__fields.fields[0],
  16, 1, kUpb_ExtMode_NonExtendable, 1, UPB_FASTTABLE_MASK(255), 0,
#ifdef UPB_TRACING_ENABLED
  "chromeos_update_engine.ApexMetadata",
#endif
};

typedef struct {
  upb_MiniTableField fields[10];
  upb_MiniTableSubInternal subs[3];
} chromeos_0update_0engine__DeltaArchiveManifest_msg_init_Fields;

static const chromeos_0update_0engine__DeltaArchiveManifest_msg_init_Fields chromeos_update_engine_DeltaArchiveManifest__fields = {{
  {3, 12, 64, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {4, 40, 65, kUpb_NoSub, 4, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)},
  {5, 48, 66, kUpb_NoSub, 4, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)},
  {12, 16, 67, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {13, UPB_SIZE(20, 56), 0, 18, 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {14, UPB_SIZE(56, 64), 68, kUpb_NoSub, 3, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)},
  {15, UPB_SIZE(24, 72), 69, UPB_SIZE(13, 14), 11, (int)kUpb_FieldMode_Scalar | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {16, 9, 70, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {17, UPB_SIZE(28, 80), 0, UPB_SIZE(8, 10), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {18, UPB_SIZE(32, 24), 71, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
 },
  {
  {.UPB_PRIVATE(submsg) = &chromeos_0update_0engine__PartitionUpdate_msg_init},
  {.UPB_PRIVATE(submsg) = &chromeos_0update_0engine__DynamicPartitionMetadata_msg_init},
  {.UPB_PRIVATE(submsg) = &chromeos_0update_0engine__ApexInfo_msg_init},
}};

const upb_MiniTable chromeos_0update_0engine__DeltaArchiveManifest_msg_init = {
  &chromeos_update_engine_DeltaArchiveManifest__fields.fields[0],
  UPB_SIZE(64, 88), 10, kUpb_ExtMode_NonExtendable, 0, UPB_FASTTABLE_MASK(248), 0,
#ifdef UPB_TRACING_ENABLED
  "chromeos_update_engine.DeltaArchiveManifest",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x000c000000000018, &upb_DecodeFast_Varint32_Scalar_Tag1Byte},
    {0x0028000001000020, &upb_DecodeFast_Varint64_Scalar_Tag1Byte},
    {0x0030000002000028, &upb_DecodeFast_Varint64_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0010000003000060, &upb_DecodeFast_Varint32_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0040000004000070, &upb_DecodeFast_Varint64_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0009000006000180, &upb_DecodeFast_Bool_Scalar_Tag2Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0018000007000192, &upb_DecodeFast_Bytes_Scalar_Tag2Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
  })
};

const upb_MiniTableEnum chromeos_0update_0engine__CowMergeOperation__Type_enum_init = {
    64,
    0,
    {
        0x7,
        0x0,
    },
};

const upb_MiniTableEnum chromeos_0update_0engine__InstallOperation__Type_enum_init = {
    64,
    0,
    {
        0x7fff,
        0x0,
    },
};

static const upb_MiniTable *messages_layout[13] = {
  &chromeos_0update_0engine__Extent_msg_init,
  &chromeos_0update_0engine__Signatures_msg_init,
  &chromeos_0update_0engine__Signatures__Signature_msg_init,
  &chromeos_0update_0engine__PartitionInfo_msg_init,
  &chromeos_0update_0engine__InstallOperation_msg_init,
  &chromeos_0update_0engine__CowMergeOperation_msg_init,
  &chromeos_0update_0engine__PartitionUpdate_msg_init,
  &chromeos_0update_0engine__DynamicPartitionGroup_msg_init,
  &chromeos_0update_0engine__VABCFeatureSet_msg_init,
  &chromeos_0update_0engine__DynamicPartitionMetadata_msg_init,
  &chromeos_0update_0engine__ApexInfo_msg_init,
  &chromeos_0update_0engine__ApexMetadata_msg_init,
  &chromeos_0update_0engine__DeltaArchiveManifest_msg_init,
};

static const upb_MiniTableEnum *enums_layout[2] = {
  &chromeos_0update_0engine__CowMergeOperation__Type_enum_init,
  &chromeos_0update_0engine__InstallOperation__Type_enum_init,
};

const upb_MiniTableFile update_metadata_proto_upb_file_layout = {
  messages_layout,
  enums_layout,
  NULL,
  13,
  2,
  0,
};

#include "upb/port/undef.inc"

