/* This file was generated by upb_generator from the input file:
 *
 *     update_metadata.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated.
 * NO CHECKED-IN PROTOBUF GENCODE */

#ifndef UPDATE_METADATA_PROTO_UPB_H__UPB_MINITABLE_H_
#define UPDATE_METADATA_PROTO_UPB_H__UPB_MINITABLE_H_

#include "upb/generated_code_support.h"

// Must be last.
#include "upb/port/def.inc"

#ifdef __cplusplus
extern "C" {
#endif

extern const upb_MiniTable chromeos_0update_0engine__Extent_msg_init;
extern const upb_MiniTable chromeos_0update_0engine__Signatures_msg_init;
extern const upb_MiniTable chromeos_0update_0engine__Signatures__Signature_msg_init;
extern const upb_MiniTable chromeos_0update_0engine__PartitionInfo_msg_init;
extern const upb_MiniTable chromeos_0update_0engine__InstallOperation_msg_init;
extern const upb_MiniTable chromeos_0update_0engine__CowMergeOperation_msg_init;
extern const upb_MiniTable chromeos_0update_0engine__PartitionUpdate_msg_init;
extern const upb_MiniTable chromeos_0update_0engine__DynamicPartitionGroup_msg_init;
extern const upb_MiniTable chromeos_0update_0engine__VABCFeatureSet_msg_init;
extern const upb_MiniTable chromeos_0update_0engine__DynamicPartitionMetadata_msg_init;
extern const upb_MiniTable chromeos_0update_0engine__ApexInfo_msg_init;
extern const upb_MiniTable chromeos_0update_0engine__ApexMetadata_msg_init;
extern const upb_MiniTable chromeos_0update_0engine__DeltaArchiveManifest_msg_init;

extern const upb_MiniTableEnum chromeos_0update_0engine__CowMergeOperation__Type_enum_init;
extern const upb_MiniTableEnum chromeos_0update_0engine__InstallOperation__Type_enum_init;
extern const upb_MiniTableFile update_metadata_proto_upb_file_layout;

#ifdef __cplusplus
}  /* extern "C" */
#endif

#include "upb/port/undef.inc"

#endif  /* UPDATE_METADATA_PROTO_UPB_H__UPB_MINITABLE_H_ */
